### ISSUE TITLE
Grasshopper_Toolkit: Making sure BHoM objects preview is working correctly for all the objects implementing the GetGeometry() method

### ISSUE THREAD

**Issue by adecler** [BHoM/Grasshopper_Toolkit#158]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
Closing this as we have a test script to continuously check the status of it.
