### ISSUE TITLE
Grasshopper_Toolkit: Display more than 15 messages

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#193]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
Moving this to feature request as it requires the implementation of a new functionality or amending a current one that is only partially covering it.

**Comment by adecler** [comment]
IT seems that this is not possible in GH.
