### ISSUE TITLE
Grasshopper_Toolkit: Add option to Explode component to explode the custom data

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#241]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
@IsakNaslundBh something to discuss if we can close this one or if you still feel this is needed

**Comment by IsakNaslundBh** [comment]
Think this can be closed. Especially given all the various ideas floating around regarding fragments etc. to be used over the custom data for the cases I thought this could be useful.
