### ISSUE TITLE
Grasshopper_Toolkit: Making 2.0 forward compatible

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#247]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
@adecler @IsakNaslundBh Is this being solved in https://github.com/BHoM/BHoM_Engine/pull/782?

**Comment by rwemay** [comment]
Think we’d need to flesh out the TimeMachine namespace before this one? ;)
