### ISSUE TITLE
Grasshopper_Toolkit: Component creation location

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#311]
The components created via the ctrl+shift+b search menu are appearing on the place of the screen where the inputs are chosen, rather than on the position of the mouse when the menu was first created. 
The second behaviour is how the standard double click menu behaves, and I think that is better, as you have no control over where the component ends up with the current implementation, and it can even appear off screen.

Gif below showing first standard GH double click behaviour, then ctrl+shift+b search menu behaviour

![search menu](https://user-images.githubusercontent.com/22005920/50769265-bcdb1180-1283-11e9-8656-1a8aa625ca51.gif)

**Comment by epignatelli** [comment]
@FraserGreenroyd @michaldengusiak @ZiolkowskiJakub is this happening also in dynamo?

**Comment by FraserGreenroyd** [comment]
Is this happening for all users? I don't know about Dynamo, but I can't replicate the issue @IsakNaslundBh is mentioning on my GH canvas?

**Comment by epignatelli** [comment]
My machine seems to be affected too, may be a win 10 issue?

**Comment by FraserGreenroyd** [comment]
I'm on Windows 10 - find the next scapegoat to blame :wink:

I might not have the latest master branch though, so it could be a recent change that's caused it.

**Comment by epignatelli** [comment]
We should get the position of the menu rather than the `CursorCanvasPosition`
https://github.com/BHoM/Grasshopper_Toolkit/blob/9ac0513910a2297c1fac7e7ed57fddf1254ff1fd/Grasshopper_UI/2.1/Global/GlobalSearch.cs#L77-L79

I'll add this into the next pr.

**Comment by ZiolkowskiJakub** [comment]
Hi @epignatelli,

As far as I remember, the ctrl + shift + b shortcut is disabled in Dynamo.

**Comment by adecler** [comment]
It is available in Dynamo but ONLY after you put at least one component in the canvas as dynamo doesn't seem to provide you with an entry point to execute code at launch. @ZiolkowskiJakub , we discussed the possibility of using an additional type of plugin for Dynamo (the one that modifies the UI directly) to take care of that problem. It might be a good one for you to look into soon.

**Comment by ZiolkowskiJakub** [comment]
Hi @adecler,

I tried it on my machine with BHoM nodes placed on canvas but still did not get the textbox....

@michaldengusiak, @FraserGreenroyd can you please check if textbox is showing for you?

Thanks.

**Comment by adecler** [comment]
@michaldengusiak , see my initial comment on this post. There is a way... just a question of Jakub having the time.

**Comment by michaldengusiak** [comment]
@adecler yes I was referring to this.. just encouraging Jakub  :)

**Comment by FraserGreenroyd** [comment]
> We should get the position of the menu rather than the `CursorCanvasPosition`
> https://github.com/BHoM/Grasshopper_Toolkit/blob/9ac0513910a2297c1fac7e7ed57fddf1254ff1fd/Grasshopper_UI/2.1/Global/GlobalSearch.cs#L77-L79
> 
> I'll add this into the next pr.

Guessing this didn't get done in the next PR then? :smile:

**Comment by epignatelli** [comment]
No, sorry - I have had problems converting screen coordinates to grasshopper canvas coordinates. The issue has then been unprioritised and that's why it is still there.

Is this creating further problems?

**Comment by FraserGreenroyd** [comment]
No, I was just combing through all of the 3.0RC tasks (which are due this week) and was re-reading the comments on this one and found that one slightly humorous 😛 

That said, if it's been de-prioritised and isn't going to be fixed this week, it might be worthwhile bumping it to 3.1 milestone?

**Comment by epignatelli** [comment]
Yep, thanks @FraserGreenroyd - going through 3.0 RC issues as we speak!

**Comment by epignatelli** [comment]
@FraserGreenroyd you got a bonus fix! #445

**Comment by FraserGreenroyd** [comment]
I love a good bonus @epignatelli ! I'll take a look today :smile:
