### ISSUE TITLE
Grasshopper_Toolkit: Name of PropertyValue components

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#313]
Could we change back the names of the `PropertyValue` components to `GetProperty` and `SetProperty`, or are there any reasons that they both have to be called `PropertyValue`?
Find those names less intuitive, and also think it would be beneficial if the components had different names!

**Comment by rwemay** [comment]
Agree with @IsakNaslundBh  on this one. Good to understand the rationale for the change and if we can go back to get/set - seems more 1:1 with {get; set;}

**Comment by adecler** [comment]
This is a BHoM_UI problem so I moved it there: https://github.com/BHoM/BHoM_UI/issues/56
