### ISSUE TITLE
Grasshopper_Toolkit: ICurve -> Geometry casting issue

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#327]
Once an ICurve is returned by a BHoM method, it has some weird issues with casting to GH geometry (see the screen below). Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FGrasshopper_Toolkit%2FGrasshopper_Toolkit-Issue327-ICurveGeometryCastingIssue).

![image](https://user-images.githubusercontent.com/26874773/52126009-708ab380-262e-11e9-86dd-baf702966e52.png)

**Comment by epignatelli** [comment]
Closing this as the problem seems to happen only in the PullPoint component. Is it correct @pawelbaran ?

**Comment by pawelbaran** [comment]
Good order - shoot first and then ask 😸 Yeah, you are right, acc. to my knowledge this happens only to PullPoint.

**Comment by epignatelli** [comment]
Ahahahahahah sorry 🥇
