### ISSUE TITLE
Grasshopper_Toolkit: Consider adding automatic Flatten attribute to Push component

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#334]
Issues have come up two times now on yammer, where the push component have been  executing slowly due to the obejcts being pushed as a DataTree rather than a list.

https://www.yammer.com/burohappold.com/threads/61626778714112
https://www.yammer.com/burohappold.com/threads/30404515225600

One simple thing we could do hopefully make these problems less frequent is to add an automatic flatten attribute to the objects input of the push component, by adding the following to the `RegisterInputParams()` method. 
```
            pManager[1].DataMapping = GH_DataMapping.Flatten;
```

Will then default to have the objects input flattened, something that can be removed from the UI just as easily as it is to add it.

What do you think?

**Comment by rwemay** [comment]
Will this make the component display the 'flatten' icon in Grasshopper, such that the user can right click and remove it/graft if necessary? 

If not then I'd worry a bit that we're over constraining.

**Comment by IsakNaslundBh** [comment]
yes, it should work exactly the same way as if you manually added flatten.

**Comment by rwemay** [comment]
I say go for it then, I think graft/unflattened will be the fringe case(s).

**Comment by FraserGreenroyd** [comment]
I regularly end up flattening inputs - I agree with @rwemay - let's do it.

**Comment by al-fisher** [comment]
Yep - agreed with above!

> it should work exactly the same way as if you manually added flatten

👍 👍 
Let’s do it!

**Comment by epignatelli** [comment]
Thanks guys! I'll action on that!
