### ISSUE TITLE
Grasshopper_Toolkit: Show list of compatible types in input descriptions

### ISSUE THREAD

**Issue by alelom** [BHoM/Grasshopper_Toolkit#339]
For some components it's not easy to guess what is the right type of input required.

For example, consider the creation of a structural `Bar`. The input `property` description says:

> property is a ISectionProperty

but for a newcomer this is not helpful in finding out what to type in the BHoM search bar next.
A novice won't find a type compatible with `ISectionProperty` straight away and might struggle looking for terms like "crossSection" or similar.

A workaround could be to have a **list of types types compatible with the input type in the input description**. This way the user would easily find e.g. the `SteelSection` as a valid input for the `property` input of `ISectionProperty`.

![image](https://user-images.githubusercontent.com/6352844/54936235-f71a8d80-4f19-11e9-82b5-5e43fc4f9e19.png)

**Comment by epignatelli** [comment]
Thanks @alelom for flagging it!

This has to be handled in the Reflection_Engine, closing this and moving it there.
