### ISSUE TITLE
Grasshopper_Toolkit: Param_ScriptVariables' menu has a `List` entry that does breaks the backend BHoM method

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#350]
`SetProperty` component provides an option to input a list (screen below). However, after clicking the option, the component crashes with the following error:

_1. This component failed to run properly. Inputs cannot be collected properly.
GetData() can only be called on a parameter with access set to GH_ParamAccess.item_

![image](https://user-images.githubusercontent.com/26874773/56886369-2c615080-6a6f-11e9-869e-744f05585001.png)

**Comment by peterjamesnugent** [comment]
@pawelbaran I had a similar error when using the `BH.Engine.Reflection.Modify.SetProperty()` method from the CTRL+SHIFT+B search bar.

If you use the SetProperty component in toolbar it should work:
![image](https://user-images.githubusercontent.com/30078587/58552498-71ada500-820a-11e9-9ea2-8089aac1acfa.png)

**Comment by epignatelli** [comment]
Thanks @peterjamesnugent for this.

I think the action here is on the BHoM_Engine side, in hiding the SetProperty method from the UI.
The method then won't appear in the CTRL+SHIFT+B menu, but the component will.

**Comment by pawelbaran** [comment]
@peterjamesnugent the exact component you mention does not work for me...

**Comment by epignatelli** [comment]
Yes, maybe. I think @rwemay also tried last week and it worked for him.

Quick call this afternoon?

**Comment by pawelbaran** [comment]
Could be - just FYI, I append a screenshot, test file is located [here].(https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FGrasshopper_Toolkit%2FGrasshopper_Toolkit-Issue350-SetPropertyDoesNotWorkWithListInputType)

![image](https://user-images.githubusercontent.com/26874773/58560249-0b824b80-8225-11e9-8d68-8a7a92f75fd5.png)

**Comment by peterjamesnugent** [comment]
Could it be to do with the CustomObject? It works for assigning tags for Nodes:

![image](https://user-images.githubusercontent.com/30078587/58562320-ec81ba80-8220-11e9-8e92-1ba9cd0c6496.png)

**Comment by epignatelli** [comment]
From the last chat with @pawelbaran, reopening this as he found a major edge case with `CustomObject`s.

**Comment by epignatelli** [comment]
Guys, is there a specific use case where you want to set the property of a `CustomObject` and, you cannot do it using the `+` and `-` on the component?

I am trying to check if this is `critical` or there is a workaround. In case there is, I'll remove this from the milestone.

**Comment by pawelbaran** [comment]
There is a workaround - one can explode and recreate the `CustomObject` from scratch, the only issue is that is laborious and inefficient. But works :)

**Comment by epignatelli** [comment]
Ok, I'll leave this in the milestone then, and if I have time, I'll fix it, otherwise, that's for the next beta.

**Comment by epignatelli** [comment]
After a little bit of digging, I think the problem here is that we should not have a `List` entry in the menu.
Basically every time we have the type `object` in the parameters of a BHoM method, that parameter gets translated into a `Param_ScriptVariable` object in grasshopper.
Each `Param_ScriptVariable`, by default, has a `List` entry in the menu. Although, the parameter in the backend method (BHoM method) is not of type `List<T>`, but object, meaning it can be anything.

As a conclusion, I would remove the `List` entry from there. The problem is that Grasshopper does not like it, I can't remove it easily from there. I can find a workaround, like using reflection or wrapping it around another parameter, that each of those has drawbacks. For now, I think we need to cope with it, just don't click on it, unless the parameter is in a `CreateCustomObject` component.

**Comment by pawelbaran** [comment]
@epignatelli not sure if I understand correctly: does it mean that for now it is impossible to set a property of a `CustomObject` when the property is a list, not an item?

**Comment by epignatelli** [comment]
There are two separate issues here:
1. The fact that we can't reflect a `List` option when the backend method does not support it. This is true for any component that comes from the morphing of a `Create` , `Convert`, `Compute`, `Modify`, `Query` component. It is fine instead if you use the `SetProperty` component
2. The fact that the `SetProperty` component does not work with the `CustomObject` component.
