### ISSUE TITLE
Grasshopper_Toolkit:  Casting Vectors

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/Grasshopper_Toolkit#357]
![image](https://user-images.githubusercontent.com/15865536/57116519-43ae7f80-6d88-11e9-9475-02ebe9baf7da.png)

A vector returned by grasshopper doesn't seem to be able to be put directly into another BHoM component unless you break it down to numbers and reconstruct it with the BHoM vector tool.  @adecler am i right in thinking there should be some sort of autocast to take care of stuff like this?

**Comment by epignatelli** [comment]
Hey!

I can't replicate the problem, everything is alright on my machine
![image](https://user-images.githubusercontent.com/26899347/57127446-604ab780-6d88-11e9-9d6f-a35ce844e523.png)


Could the problem be somewhere else in the script?

**Comment by emidio-piermarini** [comment]
![image](https://user-images.githubusercontent.com/15865536/57127904-62326c00-6dc4-11e9-9299-e3515b00d299.png)

Could it be because i'm going into a dictionary and we lose it there?  I've had this issue before as well with vectors though which is why i thought it was a more general issue, let me try to dig it out

**Comment by epignatelli** [comment]
I may be an issue, yes - Grasshopper or we may not cast it correctly. Can you send that script? I can take a look.

**Comment by rwemay** [comment]
One thing I've noticed in the past, is the need to put in BHoM or Grasshopper geometry components to force the type, Sorry I don't have specific examples, but if you try putting in a 'Geometry' component between the vector and the dictionary it might help?

**Comment by emidio-piermarini** [comment]
![image](https://user-images.githubusercontent.com/15865536/57128430-f9e48a00-6dc5-11e9-9fa7-2d79427c596e.png)

This is the other example I had before, sounds a lot like Rob's issue.  Having said that, i just checked and it seems to not be the issue any more so it may be fixed indeed.

**Comment by emidio-piermarini** [comment]
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02_Current&viewpath=%2Fsites%2FBHoM%2F02_Current%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FTekla_Toolkit%2FIssue%206

@epignatelli check out the script here

**Comment by epignatelli** [comment]
@emidio-piermarini with delay, but I tested it :D
![image](https://user-images.githubusercontent.com/26899347/58093604-bb710c80-7bc6-11e9-95aa-25df1f1b7501.png)

The C# is just `A = x.GetType()`.
Except for the Execute of Tekla, everything seems to work fine.

**Comment by epignatelli** [comment]
Guys In am closing this as it seems to work, but do shout to reopen it in case it happens again.
