### ISSUE TITLE
Grasshopper_Toolkit: GH_IBHoMGeometry should specify  GH_GeometricGoo<IGeometry>

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_Toolkit#364]
Instead of  `GH_GeometricGoo<object>`.

We have now separated the rhino entity and the bhom entity in the Geometry.

`Value` and `m_Value` always refer to a `BH.oM.Geometry.IGeometry` object
`m_RhinoGeometry` works in the background and always refers to a `Rhino.Geometry` object

**Comment by epignatelli** [comment]
Bumping this to the 2.5 RC milestone to align to https://github.com/BHoM/Grasshopper_Toolkit/pull/402#issuecomment-534558435

**Comment by adecler** [comment]
related to https://github.com/BHoM/Grasshopper_Toolkit/issues/558
