### ISSUE TITLE
Grasshopper_Toolkit: GH_BHoMObject should specify GH_BHoMGoo<BHoMObject>

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_Toolkit#365]
instead of GH_BHoMGoo<object>.

Following the amendement that brought to #364.
At the moment you can pass anything in `GH_BHoMObject` which is conflicting with its base definition. The reflection here is not symmetric, and not that transparent.
e.g. `IGeometry` is not a `BHoMObject` and should fail, whereas it currently succeeds.

Passing a `IGeometry` would work in `GH_IObject` though.

**Comment by epignatelli** [comment]
Bumping this to the 2.5 RC milestone to align to https://github.com/BHoM/Grasshopper_Toolkit/pull/402#issuecomment-534558435

**Comment by adecler** [comment]
related to https://github.com/BHoM/Grasshopper_Toolkit/issues/558
