### ISSUE TITLE
Grasshopper_Toolkit: Allow internalisation of BHoM data 

### ISSUE THREAD

**Issue by rwemay** [BHoM/Grasshopper_Toolkit#374]
A key part of a lot of workflows is to 'internalise' the json text serialised versions of the BHoM objects. At the moment, this is through a series of 'toJason' and 'fromJson' components. 

Would be really handy if we could just right click the BHoM data collection component (or any data collection component) in Grasshopper and 'internalise' and let the serialisation/deserialisation happen in the background. 

@kayleighhoude @al-fisher  FYI

**Comment by al-fisher** [comment]
Ummm... you can already do that! Right?! Unless I missed something. 😄 
@rwemay give it a try! 
There were historical issues with some isolated types when internalised as BHoM data not deserialialising correctly if you save and reopen a file. But should be good to go.
It you find it not working with some objects - we should raise an issue as is a bug! 🐛

**Comment by kayleighhoude** [comment]
Agree with @al-fisher I believe we can already do this via normal serialize functions! Got it working on Model Laundry :)

**Comment by rwemay** [comment]
Brilliant! Must have missed that one ages ago! Sorry for cluttering up your script in that case @kayleighhoude .

I havent tested but assume all ok from Kayleighs comment so will close this for now. Can always reopen if it persists.

Brilliant stuff.
