### ISSUE TITLE
Grassopper_Toolkit: panel unusual behaviour

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Grasshopper_Toolkit#376]
trying to find correct place to log this...
please see full details here
https://github.com/BHoM/BHoM_Engine/issues/1056

I tested now Dynamo to see if I have same issue as well here but Dynamo works fine

![image](https://user-images.githubusercontent.com/26113670/59947044-1fa41c00-9464-11e9-9b6e-39d622df4c5d.png)

[test file here added pictures and video](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Grasshopper_Toolkit-Issue376_PanelUnusualBehaviour?csf=1&e=NsmCcT)

**Comment by epignatelli** [comment]
Have you got a reproducible example of this? I can test it today

**Comment by michaldengusiak** [comment]
@epignatelli yes see in link above you have file, image and video...what I did

**Comment by epignatelli** [comment]
I am afraid there is no file in the issue though.

**Comment by michaldengusiak** [comment]
it is there under image I just copied link here again
[# test file here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Grasshopper_Toolkit-Issue376_PanelUnusualBehaviour?csf=1&e=NsmCcT)

**Comment by epignatelli** [comment]
Thanks @michaldengusiak  - I still need the Revit file you're pulling stuff from though.

**Comment by adecler** [comment]
@michaldengusiak , can you provide a self contained example that reproduce this problem?

**Comment by michaldengusiak** [comment]
@adecler I run the test
this script is from July and I had to replace all nodes to get this working...incredible how fast we change
however when I run it, this is working fine..  so I am closing this one
![image](https://user-images.githubusercontent.com/26113670/65598407-3ee6a400-df93-11e9-9a54-5a763e739480.png)

**Comment by adecler** [comment]
Thanks @michaldengusiak 👍
