### ISSUE TITLE
Grasshopper_Toolkit: Check compatibility with Rhino 6 and update nugets, eventually 

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_Toolkit#383]

**Comment by FraserGreenroyd** [comment]
"Eventually" :smile:

**Comment by alelom** [comment]
As discussed with @epignatelli, compatibility with Rhino6 has been implied but never officially supported. 

Before officializing Rhino6 support, I'd like to put together and test a set of scripts that must work with that version. I am happy to open and test them personally with my licence of Rhino6, however I'd like to ask the relevant responsibles to help me collect for their repos.

**Comment by alelom** [comment]
As discussed with @al-fisher we'll bump this into the next milestone such as the toolkit leads can create and help collect the scripts ready to be tested for the next quarter

**Comment by alelom** [comment]
After we discovered and solved the problem with the different geometry conversions between Rhino5-Rhino6 with https://github.com/BHoM/Rhinoceros_Toolkit/pull/148, we can probably go back to say that the compatibility is ok.

**Comment by epignatelli** [comment]
Thanks @alelom, I will announce on Teams we have fixed this. 
Closing this in the meanwhile, we can reopen if something else pops up.

**Comment by FraserGreenroyd** [comment]
> "Eventually" 😄

I still like this response to this issue @epignatelli :wink:
