### ISSUE TITLE
BHoM_Engine: Reflection_engine - return more meaningful, user friendly error when SetPropertyValue fails

### ISSUE THREAD

**Issue by alelom** [BHoM/Grasshopper_Toolkit#395]
#### Description:
Someone today was having difficulty in using the [`SetPropertyValue()` method](https://github.com/BHoM/BHoM_Engine/blob/d397534e9ae4f1ef510a39cfb8b535ccc723020a/Reflection_Engine/Modify/SetPropertyValue.cs#L39-L49) in Grasshopper, trying to specify a list of objects into the input `value` without right-clicking and specify type `list`. I was asked for help and I was confused too, end up looking for a method that could accept a List as an input, when the only available solution was the right click to specify the type.

See proposed change:
```c#
[Description("Set the value of a property with a given name for an object")]
[Input("obj", "object to set the value for")]
[Input("propName", "name of the property to set the value of")]
[Input("value", "new value of the property. Right click on the input to specify if it's of type `item` or `list`.")]
[Output("result", "New object with its property changed to the new value")]
public static BHoMObject PropertyValue(this BHoMObject obj, string propName, object value)
{
    BHoMObject newObject = obj.GetShallowClone() as BHoMObject;
    try
    {
        newObject.SetPropertyValue(propName, value);
    }
    catch (Exception e)
    {
        BH.Engine.Reflection.Compute.RecordError("Could not set property. Did you set the correct `value` type? Right click on the input to set it to `item` or `list`."
            + " Exception message: " + Environment.NewLine + e.Message);
    }
    return newObject;
}
```

### In general
If a component input is right-clickable, I think that should be explicitly stated in the tooltip text and a meaningful error returned if that is failing because of that.

**Comment by alelom** [comment]
> The error is quite meaningful I think:
> `Cannot convert Foo to List<Foo>` or something like that?

Agree, the error itself is meaningful, but it does not give any info on how it should be solved: you could still think you're using the wrong component -- which is the case more often than not, I think?
What I'm really trying to say is that the right click- set type is really an "additional input" which is hidden in the right click context menu -- for that we should really make clear when that's available

**Comment by adecler** [comment]
Just make sure to remember that we have various UIs when solving this issue. So right-click might be meaningless in some of them.

**Comment by adecler** [comment]
Now moved to https://github.com/BHoM/BHoM_Engine/issues/1218
