### ISSUE TITLE
Grasshopper_Toolkit: Rhino crash with custom component with old types

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#396]
#### Description:

If you have a `CreatCustom` component on the canvas targeting a type that is then changed (name/namespace), deleteing this component causes a full Rhino crash.

After investigation with @epignatelli the root of the problem seem to be a missing null check for types making the `CompileInputGetters` in the BHoM_UI crash.

Updating method in `Type` method in Grasshopper_Engine to

```

     public static Type Type(this IGH_Param param, Caller caller = null)
        {
            Type type;

            if (param == null)
                type = typeof(object);

            if (param is Param_ScriptVariable)
                type = Type(((Param_ScriptVariable)param).TypeHint, param.Access);

            else if (caller != null)
                type = (caller.InputParams.Find(x => x.Name == param.NickName))?.DataType;

            else
                type = param.Type;

            if (type == null)
                return typeof(object);
            else
                return type;
        }
```
stops the crash, but not sure if it has further implications.

#### How to replicate:

1. Create a BHoMObject using CustomObject
2. Change the object name/namespace
3. try delete/update the component

#### Expected behaviour:

For rhino not to crash.

**Comment by epignatelli** [comment]
@alelom I am gonna take care of this, as I already spoke with @IsakNaslundBh and have the code ready
