### ISSUE TITLE
Grasshopper_Toolkit: Pull should return warning for missing FilterRequest input OR not require a FilterRequest at all (default: retrieve all IBHoMObjects)?

### ISSUE THREAD

**Issue by alelom** [BHoM/Grasshopper_Toolkit#397]
#### Description:
Just dumping here a reminder for possible UI improvements.

As per title. I found myself multiple times not remembering which `FilterRequest` I should use to "just pull all items". I've always found this behaviour confusing: 
![image](https://user-images.githubusercontent.com/6352844/63781122-2d9d6f80-c8e1-11e9-9b36-c24d9501d7ff.png)

We've already had a conversation about this. I remember that the conclusion was that this behaviour is not enforced because "what does 'just pull all items' even mean", implying that one would never want to pull down all objects (IBHoMObjects) together with, e.g. all the results (IObjects). 

However, this forces the users to do this:
![image](https://user-images.githubusercontent.com/6352844/63781939-7f92c500-c8e2-11e9-9afc-c44f1ba484f5.png)
which is confusing/blocking for new users -- the component should at least mention how to create the most common FilterRequest.

For this reason I propose one of the two:
- that the default behaviour for no FilterRequest specified should be to pull all IBHoMObjects (leaving out IObjects); add a _note_ to explain this behaviour (`BH.Engine.Reflection.Compute.RecordNote`), OR
- that a warning is issued if no FilteRequest is input, stating what should be input in order to pull all IBHoMObjects (which is by far the most common use case); for example, `"Please input a FilterRequest. To pull all IBHoMObjects, look for 'Create FilterRequest(type, string)' and just insert the IBHoMObjects type."`

@al-fisher (another item for our UI improvs chat perhaps?)

**Comment by epignatelli** [comment]
At the moment, the pull component automatically instantiates a default `FilterRequest` if none is provided.
https://github.com/BHoM/BHoM_UI/blob/d065743b720aa171b442b91de4b07da27974509b/BHoM_UI/Components/Adapter/Pull.cs#L88-L97

I think that it means that the decision of the "pull all" is delegated to the individual adapters to avoid weird behaviour (what would "pull all" mean with an HTTPAdapter?).

Maybe this is an issue with he specific adapter you are using?

**Comment by rwemay** [comment]
Yes, I think it's on the side of the adapter implementations what happens with no filterrequest. For example, if nothing is input to the Delete component for Robot, it will clear the structure. One of the reasons for not enabling 'pulling all objects' is the time it takes for this depending on software/model size. 

My personal preference would be to enable pull all on adapters, and for that to be adapter dependent but with some guidelines. For example, I don't think analysis adapters should pull results with a 'pull all'.

**Comment by adecler** [comment]
I have now raised the issue in the appropriate repo: https://github.com/BHoM/BHoM_Adapter/issues/133
