### ISSUE TITLE
Grasshopper_Toolkit - Node Geometry Preview Incorrect

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/Grasshopper_Toolkit#399]
#### Description:

Nodes' geometry do not show correctly in the perspective view.  The seem to still work in the other views however.

Incorrect location shown for nodes' geometry (point) preview:
![image](https://user-images.githubusercontent.com/15865536/63841277-19c33d80-c9b5-11e9-8fe9-1d09f773b1e9.png)

Correct location if you use the native ghop points:
![image](https://user-images.githubusercontent.com/15865536/63841289-20ea4b80-c9b5-11e9-8ddb-69856684582e.png)

Ok in top view (and other ortogonal views):
![image](https://user-images.githubusercontent.com/15865536/63841407-53944400-c9b5-11e9-9689-42b3b46e1071.png)

#### How to replicate:

Create some nodes and look at the preview of their geometry in green mode in perspective view

**Comment by epignatelli** [comment]
I think it is grasshopper messing with the cameras.
Can you try disabling the bump preview?
https://www.grasshopper3d.com/forum/topics/everything-you-need-to-know-about-displaying-in-grasshopper?commentId=2985220%3AComment%3A1090490

**Comment by emidio-piermarini** [comment]
@epignatelli for the win!  That was it!  So really this isn't an issue with the code then ya?

**Comment by epignatelli** [comment]
Yeah, at least not our code ahahah

Grasshopper is trying to be clever by phisically moving its objects closer to the camera, in order to overshadow the underlying rhino objects.
There might be a way for us to disable that by default, or use a display mode that works around it, but I need to check.

I'll keep this open and pip it up, so that people can easily find it, thanks @emidio-piermarini !

**Comment by rwemay** [comment]
Brilliant, I noticed this too, put it down to a GH/Rhino behaviour - now I know, thanks!

**Comment by emidio-piermarini** [comment]
It was so annoying!

**Comment by epignatelli** [comment]
Closing this because there is nothing we can do. Hopefully it will still stay pinned. If not so, I'll reopen it.
