### ISSUE TITLE
Grasshopper_Toolkit: Explode bars causing crash

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Grasshopper_Toolkit#403]
### Description:
Bars coming out of various FEA adapters, when fed to explode(), crash grasshopper. 

#### How to replicate:
Pull bars from an FEA package and explode them. Sometimes it works fine other times it crashes, even if you only explode a single bar.

#### Expected behaviour:
Explode() shouldn't crash

#### Test file(s):
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Issue403-ExplodeBarsCrash?csf=1&e=wudePW

**Comment by epignatelli** [comment]
@JosefTaylor can you provide a reproducible example? I cannot reproduce the issue with what I have.

![image](https://user-images.githubusercontent.com/26899347/64433779-0bf97080-d0b7-11e9-80ec-084906bc4493.png)

**Comment by JosefTaylor** [comment]
Yeah, it's not consistent. @mchaf is working on a test script and model for you.

**Comment by epignatelli** [comment]
Wonderful, thanks very much guys

**Comment by JosefTaylor** [comment]
It happens on ETABS and RAM for sure. I'm not sure if it's a problem with both of those, or with GH

**Comment by mchaf** [comment]
I've added a test script and model here:
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=wudePW&cid=01965ccd%2Defbd%2D4101%2Dbe01%2Dde6a614274c3&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FGrasshopper%5FToolkit%2FIssue403%2DExplodeBarsCrash&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

**Comment by epignatelli** [comment]
@mchaf does this happen also in Robot? I cannot install ETABS unfortunately.

**Comment by alelom** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/6352844/64436656-b627c700-d0bc-11e9-972c-3b8b319a0e24.png)

I wonder, do you have all the latest versions of the other repos right? I think I might have encountered this right after the Fragments implementation when I didn't correctly update everything

**Comment by alelom** [comment]
@JosefTaylor any update on this?

**Comment by JosefTaylor** [comment]
It's a fresh install on @mchaf's computer. He just now compiled from code for the first time. I'll see if it happens on mine with the same model

**Comment by JosefTaylor** [comment]
Confirmed it happens on my machine too, which is a recent build. I do have old BHoM stuff lingering around which will be my next step to clean up and try this again.

**Comment by epignatelli** [comment]
Uhm, it is difficult to say what is happening from here.
Would you mind attach Visual Studio to the Rhino process and see what exception is this actually triggering?

Make sure that you have all Exceptions selected for CRL, in the `Exception Settings` tab.

**Comment by adecler** [comment]
The crash happens in BH.Engine.Structure.Query.Geometry:

![image](https://user-images.githubusercontent.com/16853390/65596402-af3ef680-df8e-11e9-8778-e79da5d7fd2c.png)

Here's the stack: 

![image](https://user-images.githubusercontent.com/16853390/65596578-12308d80-df8f-11e9-97d0-645500b0b39b.png)

So the problem is clear: This method should be called `IGeometry` method instead and the fallback method `Geometry(object o)` is missing.

**Comment by IsakNaslundBh** [comment]
Thanks @adecler . WIll raise issue and fix in structures engine straight away

**Comment by adecler** [comment]
issue raised alreaedy
