### ISSUE TITLE
Grasshopper_UI: Update description for UpdateVersion component

### ISSUE THREAD

**Issue by LivAndersson** [BHoM/Grasshopper_Toolkit#404]
Update output description to 'Define if update was successful' to align with other components in BHoM_UI.

**Comment by epignatelli** [comment]
Transferring this issue to the Grasshopper_Toolkit repo, as it is relevant only there.
Also note that this will be closed by https://github.com/BHoM/Grasshopper_Toolkit/pull/401 as per https://github.com/BHoM/Grasshopper_Toolkit/pull/401#issuecomment-528360505

**Comment by adecler** [comment]
The UpdateVersion component has now been removed by #414 .
