### ISSUE TITLE
ToString() method should use the Engine.Reflection.ToText method

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_Toolkit#406]
#### Description:

For each `Goo`, the `ToString()` method should use the `Engine.Reflection.ToText` method to enhance the way we display objects in panels.

For example, a Rhino point is displayed in a panel as `{x, y, z}`. We should do the same for the BHoM.

**Comment by adecler** [comment]
@epignatelli , I am not sure I follow your logic. `Engine.reflection.ToText` is currently used for things like Type and MethodBase, not actual instances of objects.

Agreed on the need to have a more centralised place to convert to string though (i.e. in the Engine) as we want this to be uniform across all UIs.

**Comment by epignatelli** [comment]
Yes, @adecler your second paragraph is the point of the issue. It doesn't have to be the `ToText` method, although it was the first thing I thought of.

**Comment by epignatelli** [comment]
Note the corresponding issue in the BhoM_Engine: https://github.com/BHoM/BHoM_Engine/issues/1189
