### ISSUE TITLE
Grasshopper_Toolkit: CreateType loses its banner

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Grasshopper_Toolkit#419]
#### Description:
CreateType component has a little banner to show the selection, which dissapears after re-opening the GH definition or copying and pasting the component.

![Both of these components have a type selected](https://user-images.githubusercontent.com/7024203/66080030-42e66900-e533-11e9-9f3f-0ff3739b33e5.png)

#### How to replicate:

1. place a CreateType component on the canvas
2. select a type
3. save the definition
4. close the definition
5. reopen the definition

or:

1. place a CreateType component on the canvas
2. select a type
3. copy the component
4. paste the component

#### Expected behaviour:
the banner should remain visible

#### Test file(s):
oh come on, you can do it :)

**Comment by rwemay** [comment]
hehe. I love the test file :)

**Comment by JosefTaylor** [comment]
@rwemay I was already overdoing it with the steps to duplicate the problem; I didn't want to put a single component script on OneDrive!
