### ISSUE TITLE
Grasshopper_Toolkit: low priority error overwriting the colour of the component

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Grasshopper_Toolkit#422]
#### Description:
If the code gets error in this order 
`Engine.Reflection.Compute.RecordNote("Note")`
`Engine.Reflection.Compute.RecordError("Error")`
the component will not turn red as it has already been set to Gray by `RecordNote()` potentially hiding problems that the user needs to know

#### Expected behaviour:
Make sure that the colour code for the component is sorted by priority and isn't dependent on the order within the code

**Comment by epignatelli** [comment]
Duplicate of #480
