### ISSUE TITLE
Grasshopper: Some surprising number rounding

### ISSUE THREAD

**Issue by adecler** [BHoM/Grasshopper_Toolkit#423]
#### Description:

In the case shown below, the real value of `Iy` is 6.8100000000000003E-09. It will show in GH as 6.81e-09 which could be argued either way if it is valid or not. Where it becomes a bit more problematic and worry inducing is the case of the output B below where the result is displayed as 0.0 while we would expect 3E-16.

![image](https://user-images.githubusercontent.com/16853390/66627697-10bdc100-ec2f-11e9-8204-37f65d420f7a.png)

Note that a new console application in pure C# would give the following result: 

```
double a = 6.8100000000000003E-09;

a * 1e9              --->  6.81
a - 6.81e-09         --->  0
(a * 1e9) - 6.81     --->  8.88178419700125E-16
((a*1e9)-6.81)*1e16  --->  8.88178419700125
```

So not perfect either  (since the second line gives us 0 and we don't get the expected 3E16 on the third line)
This is why I tagged this as a question as well. I am wondering if this is not a typical problem of numerical error inherent to floating numbers. GH just happens to have a few more intermediate steps that increase the problem further. If at all possible, it would be nice to be closer to what raw C# gives us though.

**Comment by epignatelli** [comment]
I think it is partly a display problem and partly a floating point approximation problem.

In the Grasshopper C# component reinstate the `out` output parameter and try doing `Print(C.ToString())`. It will give you the console equivalent `8.88178419700125`. It's just grasshopper truncating the `float64`.

![image](https://user-images.githubusercontent.com/26899347/66637548-28834e00-ec0b-11e9-8a5f-829bdb40e4d7.png)

This is python instead. It has one more significant digit:
```python
x = 6.8100000000000003e-09
A = (x * 1e9) == 6.81;
B = (x * 1e9) - 6.81;
C = ((x * 1e9) - 6.81) * 1e16;
print(A)
print(B)
print(C)

# Output
# ---
# False
# 8.881784197001252e-16
# 8.881784197001252
```
![image](https://user-images.githubusercontent.com/26899347/66637762-9465b680-ec0b-11e9-8c41-85a8802a39b1.png)
