### ISSUE TITLE
Grasshopper_Toolkit: Rhino crashes when trying to mouse over preview some JSON strings

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#454]
#### Description:

For some particular JSON strings, when hovering over the output of a ToJson component, the display fails leading to a full Rhino crash. I am not sure if this is something we can solve on our end, or something hidden to far in the GH framework.

The problem seem to be less potent in Rhino 6. Nothing can still be seen, see snip, but it does not crash Rhino.

![image](https://user-images.githubusercontent.com/22005920/72156953-0a1e2180-33b7-11ea-943d-93ae1aef6b14.png)

#### How to replicate:

Use ToJson on some specific objects and hover the mouse over the output

#### Expected behaviour:

For Rhino not to crash. If this _can_ be fixed our end I think that would be good. Think displaying something useful is definitely out of our control (and crashing might be as well).

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Grasshopper_Toolkit-Issue454-RhinoCrashingWhenDisplayingJSON?csf=1&e=dfaGoG

**Comment by adecler** [comment]
I don't think there is much that can be done here. The problem lies with The GH panel and happens with any large text
