### ISSUE TITLE
Grasshopper_Toolkit: Adding to Objects

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Grasshopper_Toolkit#456]
#### Description:
The ability to remove object inputs has been implement, the option to add inputs should be possible.
![image](https://user-images.githubusercontent.com/34092831/72890137-2d2ac880-3d09-11ea-98da-d41311f3a617.png)

**Comment by epignatelli** [comment]
This has been explicitly avoided because it is unreliable to re-type the name of the property.

You can right click on the component and use the `Add/Remove inputs` menu to re-add them.
