### ISSUE TITLE
Compliance issues

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Grasshopper_Toolkit#470]
The following compliance issues have been found for this repository. Please see the checklist below.
#### Compliance issue for HasValidCopyright
 - [x] Copyright message is invalid in Grasshopper_Toolkit\Grasshopper_UI\Components\UI\Cluster2Node.cs at line 1, column 0 
 - [x] Copyright message is invalid in Grasshopper_Toolkit\Grasshopper_UI\Templates\IBHoMParam.cs at line 1, column 0 

#### Compliance issue for NameMatchesFileName
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 38, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 55, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 79, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 86, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 93, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 100, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 110, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 117, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 124, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 131, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 141, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Compute\RenderRhinoMesh.cs at line 154, column 27 
 - [x] Method name must match file name in Grasshopper_Toolkit\Grasshopper_Engine\Query\RenderColor.cs at line 34, column 28 

#### Compliance issue for IsValidConvertMethodName
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in Grasshopper_Toolkit\Grasshopper_Engine\Convert\FromGoo.cs at line 36, column 24 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in Grasshopper_Toolkit\Grasshopper_Engine\Convert\ToGoo.cs at line 43, column 30 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in Grasshopper_Toolkit\Grasshopper_Engine\Convert\ToGoo.cs at line 53, column 36 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in Grasshopper_Toolkit\Grasshopper_Engine\Convert\ToGoo.cs at line 60, column 44 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in Grasshopper_Toolkit\Grasshopper_Engine\Convert\ToNode.cs at line 45, column 28 
 - [ ] Convert method name invalid: Method name must begin with either 'To' or 'From' and not be 'ToBHoM' or 'FromBHoM' in Grasshopper_Toolkit\Grasshopper_Engine\Convert\ToNode.cs at line 57, column 28

**Comment by epignatelli** [comment]
Checkign the boxes of the `IsValidConvertMethodName` check  in the light of https://github.com/BHoM/Test_Toolkit/pull/158
