### ISSUE TITLE
Note covers all other messages

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#480]
#### Description:
When Reflection records a Note, it appears on top of all other messages incl. errors, also overriding the balloon colour:

![image](https://user-images.githubusercontent.com/26874773/76082423-a88bc500-5fab-11ea-8454-bfd9679fd977.png)

Shouldn't the hierarchy be:
- Error
- Warning
- Note

**Comment by adecler** [comment]
I am afraid this is an issue you would have to raise with Grasshopper. As far as I know we don't have a way to control the hierarchical order. I have change the label to a question to reflect that.

**Comment by adecler** [comment]
I have actually been wondering about using the `Note` level at all. I I remember correctly, Dynamo doesn't support it anyway and it is likely other UIs will be limited to two levels. So it might be better to consider that notes are warnings in all problematic UIs

**Comment by al-fisher** [comment]
Yeah. This makes sense to me - sticking to just two levels. 
If the message is important enough to “interrupt” the workflow by popping up - it can perhaps always be reasonably be called a warning (or error of course)

**Comment by pawelbaran** [comment]
Agreed, all above makes sense to me - in this case, should I rename the issue to _Deprecate RecordNote method_ or similar?

**Comment by al-fisher** [comment]
Sounds good to me. Thanks @pawelbaran

**Comment by pawelbaran** [comment]
Closing this one, reopened as #481

**Comment by alelom** [comment]
How I had solved this in my previous experience is collecting the errors to be reported and making sure that the grasshopper component prints out first the one with the highest priority (Error, then Warning, then Note). This always worked for me. 

I generally disagree with sticking with two level. I always used the Note to describe non-critical things like automatically-instantiated object that have not been specified explicitly. No reason to worry an user with Warning if they don't specifiy, for example, an AdapterConfig, see https://github.com/BHoM/Revit_Toolkit/pull/594#issue-387323292. Remember that to reduce Recalcitrance you have to have users in mind!

**Comment by kThorsager** [comment]
Similar issue #422

**Comment by al-fisher** [comment]
@alelom - I do think you raise some valid points above. 
Is this worth including in the already planned UI workshop for end of milestone?
@adecler @pawelbaran
