### ISSUE TITLE
Output of Geometry method cannot be processed correctly by native GH components

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#489]
#### Description:

After querying a BHoM object for `Geometry`, in some cases the output cannot be used by native GH components (working fine for `Bar`, crashed for `Panel`):

![image](https://user-images.githubusercontent.com/26874773/76867172-727cf980-6865-11ea-95da-c88f12b728b9.png)

#### Test file(s):

On [SharePoint]()

**Comment by adecler** [comment]
This is a Geometry_Engine issue: https://github.com/BHoM/BHoM_Engine/issues/1616
Closing here as solving that issue will fix the problem.
