### ISSUE TITLE
Grasshopper Goo and `FromRhino()` method: FromRhino() for Sphere fails

### ISSUE THREAD

**Issue by alelom** [BHoM/Grasshopper_Toolkit#502]
#### Description:

While doing https://github.com/BHoM/BHoM_Engine/issues/1694, I tried to simply connect a Rhino/Grasshopper Sphere to the FromRhino component for testing.

This always fails:
![image](https://user-images.githubusercontent.com/6352844/80708310-61b9d780-8ae3-11ea-94d4-0c968cf2c00c.png)

I tried to follow through the code and all goes well until we get to the `FromGoo` method in Grasshopper – hence Grasshopper_Toolkit is probably the right place for this:
![image](https://user-images.githubusercontent.com/6352844/80708627-e7d61e00-8ae3-11ea-9bf2-795d57de1674.png)

The dynamic dispatch generates an Exception:
![image](https://user-images.githubusercontent.com/6352844/80708673-f9b7c100-8ae3-11ea-9641-49c13638f95b.png)

which is confusing to me.

#### Expected behaviour:

The component should return a BH.oM.Geometry.Sphere.

**Comment by adecler** [comment]
related to https://github.com/BHoM/Grasshopper_Toolkit/issues/544 ?

**Comment by alelom** [comment]
> related to #544 ?

I think so yes.
