### ISSUE TITLE
Grasshopper_Toolkit: Updating access type when versioning

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Grasshopper_Toolkit#518]
#### Description:

When versioning a method input from a `T` to a `List<T>`, (with the same name) one gets this error:
```
1. This component failed to run properly. Inputs cannot be collected properly.
GetDataList() can only be called on a parameter with access set to GH_ParamAccess.list
```

Which implies that the inputs are getting updated, but not their access type.

might be related to #411 ? but unsure.
#### Steps to reproduce:

Version any method from a item input to a list input.
Keep the name of the input the same as that keeps the wire connected and the component breaks

#### Expected behaviour:

I would like versioning to work and not brick the components.

#### Test file(s):

Can't really add testfile as I did not merge anything where the versioning fails.

**Comment by IsakLarbornBH** [comment]
Hi! I was wondering if there are any plans to get around to this soon? I've got a PR now and more planned that depend on this being fixed, or everyone's ModelLaundry scripts are going to break when they update. I've also experienced this problem before when trying to run old scripts. I'd appreciate it if you could have another look :)

**Comment by IsakLarbornBH** [comment]
Just noticed that the error I've been getting is actually subtly different, despite me trying to do the same thing that @kThorsager was trying to do. 

<img width="528" alt="Screenshot 2021-01-18 112832" src="https://user-images.githubusercontent.com/72074998/104909960-89f2aa80-5980-11eb-8475-f120d15b07ec.png">

<img width="542" alt="Screenshot 2021-01-18 112857" src="https://user-images.githubusercontent.com/72074998/104909970-8fe88b80-5980-11eb-98c5-f2ca3df2c7e5.png">

So in the current version the issue has been reversed, somehow? Seems like list access is properly set in the GH component, judging by "elements2d as list" but for some reason it's calling `GetData()` which is the opposite of what was happening to @kThorsager,`GetDataList()` being called on an input with item access.
