### ISSUE TITLE
CreateCustom does not convert breps

### ISSUE THREAD

**Issue by LMarkowski** [BHoM/Grasshopper_Toolkit#529]
#### Description:

While creating `CustomObject` with `CreateCustom` rhino geometry seems not to be converted to any `BHoMObject` but stored in the object properties as rhino object instead.

#### Steps to reproduce:

Create `CustomObject` from a brep.

#### Expected behaviour:

Should convert brep to BHoM Geometry.

#### Test file(s):

[Test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FGrasshopper%5FToolkit%2FGrasshopper%5FToolkit%2DIssue529%2DCreateCustomDoesntConvert)

**Comment by LMarkowski** [comment]
@al-fisher fyi

**Comment by adecler** [comment]
Closing as replaced by #543
