### ISSUE TITLE
BH.Adapter.Socket.SocketAdapter component didn't work until I built the Socket_Toolkit project. 

### ISSUE THREAD

**Issue by KIMGEONUNG** [BHoM/Grasshopper_Toolkit#531]
#### What is missing/incorrect?

 The BH.Adapter.Socket.SocketAdapter component in grasshopper didn't work until I built the Socket_Toolkit project. So, I presume the BH.Adapter.Socket.SocketAdapter needs the build result of the Socket_Toolkit project. But, dependencies.txt file does not have Socket_Toolkit project, and there seems to be no such information anywhere else. I hope this information is included somewhere.

**Comment by al-fisher** [comment]
Hi @KIMGEONUNG  - yes, you are correct in that the BH.Adapter.Socket.SocketAdapter needs the build result of the Socket_Toolkit project.

When loading the BHoM UI in Grasshopper it will simply load any oM, Engine and Adapter dlls in the central `C:\ProgramData\BHoM\Assemblies` folder.

Any toolkit, like the Sockets_Toolkit, when being built will therefore be responsible for copying it's own dlls into that central folder to be loaded.

Grasshopper_Toolkit is therefore not _dependant_ on Socket_Toolkit in that sense. This keeps the Grasshopper Toolkit independant and means anyone can include which ever additional Toolkits they like or need.

Hope makes sense?

Toolkits that _do_ explicitly depend on Sockets - should have it listed in there own dependencies file as you say. See [Revit_Toolkit for example](https://github.com/BHoM/Revit_Toolkit/blob/master/dependencies.txt)


You can find more information about build order and dependencies here: https://github.com/BHoM/documentation/wiki/Getting-started-for-developers
with Socket_Tookit listed under Optional base repos.

**Comment by KIMGEONUNG** [comment]
@al-fisher  I understand the context you described. I am not familiar with BHoM yet, so I think I asked this question. Thank you for your kind answer~!

**Comment by al-fisher** [comment]
No problem - do feel free to reach out with other questions and suggestions as you experiment with BHoM.
