### ISSUE TITLE
Disabling and enabling a CreateCustom component causes the name of the first property to be changed to object

### ISSUE THREAD

**Issue by harrilewis** [BHoM/Grasshopper_Toolkit#533]
#### Description:
When a CreateCustom component is disabled and then re-enabled the name of the first property seems to change to object.

#### Steps to reproduce:
Step 1:
![image](https://user-images.githubusercontent.com/585715/92246683-039c6700-eebe-11ea-9a7f-6007add81670.png)
As expected

Step 2:
![image](https://user-images.githubusercontent.com/585715/92246722-131bb000-eebe-11ea-96f9-74b9c4d569ab.png)
As expected

Step 3:
Re-enable the component
![image](https://user-images.githubusercontent.com/585715/92246812-33e40580-eebe-11ea-927d-ee1e43bd6490.png)
Warning in explode component to update outputs - not expected

Step 4:
![image](https://user-images.githubusercontent.com/585715/92246910-51b16a80-eebe-11ea-8858-5a0c2f0c3a50.png)
After update the first property is renamed to "object"

#### Expected behaviour:
At step 3 the object names are the same as before.

#### Test file(s):
[disable issue.zip](https://github.com/BHoM/Grasshopper_Toolkit/files/5175190/disable.issue.zip)

**Comment by adecler** [comment]
Hi @harrilewis ,

Thanks for reporting the bug. We have just gone through a major refactoring that should fix a decent amount of bugs (and hopefully not create too many others). I have just tested on this new version and it seems that bug doesn't appear:

![CreateCustom_FirstPropBug](https://user-images.githubusercontent.com/16853390/92300992-2e57ef80-ef92-11ea-8644-645166ecbe6c.gif)

That refactoring should be merged this week (w/c 7th Sept.) but if you want to check it up before, you can have a look at this PR: https://github.com/BHoM/Grasshopper_Toolkit/pull/530

Note, if you are using the beta installer, that a new beta will be created at the end of this month.

**Comment by harrilewis** [comment]
Hi @adecler ,

Thanks for the response. I'll give it a test after the refractoring. I was building from source using the master branch.
