### ISSUE TITLE
Changing input name of CreateCustom component doesn't trigger a run

### ISSUE THREAD

**Issue by adecler** [BHoM/Grasshopper_Toolkit#536]
#### Description:

![image](https://user-images.githubusercontent.com/16853390/93304959-697ade00-f830-11ea-8292-a4154d583aac.png)

#### Steps to reproduce:
Just change any input name of an input of CreateCustom component

#### Expected behaviour:
Component should re-run

**Comment by al-fisher** [comment]
Just uncovered this bug too :smile: - good to see already logged.
