### ISSUE TITLE
Some explode components not tracking data through

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Grasshopper_Toolkit#542]
#### Description:
This was found during testing of the 200917 alpha.

Some explode components are not keeping track of the data going through them correctly, despite data existing on the input to the explode, and some wires remaining with data passing down them.

When the output is updated, the wires which were not previously passing data are disconnected from the components.

#### Steps to reproduce:
This was discovered when running the test procedure for XML_Toolkit for CI/CD today. See the gif below for a representation of the above in visual form.

Take a copy of the test script from the link below, open the script, and set the toggle to true (toggle marked as 2.5). A couple of the wires for the explode do not keep the data passing through, and when updated remove the wires all together.

#### Expected behaviour:
I would expect the wires to keep the right data passing down through components. I would also expect that updating the output did not remove wires.

#### Test file(s):
Please take copies to avoid corruption of test files currently being used for alpha testing :smile:

[Folder to XML Toolkit test files is here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0032%5fXML%5fToolkit&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302)

You may wish to follow the test procedure (section 2) for the XML_Toolkit for CI/CD, [which can be found here](https://burohappold.sharepoint.com/:w:/r/sites/BHoM/_layouts/15/Doc.aspx?sourcedoc=%7BFF8843E3-FE42-4D35-9E7F-CAF9BFED4EDB%7D&file=0001_CICD%20-%20XML%20Toolkit.docx&action=default&mobileredirect=true) - this will detail what you need to change in the script below (and download additionally from the folder above) to get the script to the state I had it in when I found this issue.

[XML Toolkit Script shown in the gif is here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v3.3/0032_XML_Toolkit/XML_Toolkit_PushCSProject.gh?csf=1&web=1&e=zSkDGP)

[GIF COMING SOON - NEED TO RESTART LAPTOP TO GET SOFTWARE TO MAKE IT!]

**Comment by adecler** [comment]
Found the bug:

![image](https://user-images.githubusercontent.com/16853390/93582402-ff4f6e00-f9d4-11ea-8b9e-57469b63f797.png)


Similar to https://github.com/BHoM/BHoM_UI/issues/307, keeping open as it would be great to have extra protection against non-compliant code. Turning it into a feature though

**Comment by adecler** [comment]
Now closing as properly referenced in https://github.com/BHoM/BHoM_UI/issues/307
