### ISSUE TITLE
Grasshopper_Toolkit: No preview of loft, pipes

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#554]
#### Description:
There is no BHoM preview of lofts and pipes, possibly other non-planar surfaces too.

#### Test file:
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FGrasshopper%5FToolkit%2FGrasshopper%5FToolkit%2DIssue554%2DSurfacePreview&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

**Comment by adecler** [comment]
This all seem to be working now:

![image](https://user-images.githubusercontent.com/16853390/108585249-5e4d5080-7382-11eb-9574-8ee97b575cda.png)
