### ISSUE TITLE
Grasshopper_Toolkit: Explode of List of obejcts does not explode the lists

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#559]
#### Description:

When exploding an object that has a proeprty that is a nested list, you get a list of the list obejcts back:

![image](https://user-images.githubusercontent.com/22005920/96874304-428a7a00-1476-11eb-90ce-b29de097d019.png)

For an expert user, a simple c# component will `A = x;` will resolve it, but for regular users I am not sure they would be able to handle this.

#### Steps to reproduce:

Create a custom obejct with a Tree input, profive a tree and explode it.

#### Expected behaviour:

For the nested lists to be exploded into a DataTree.

Also important to keep in mind for this case what happens if you try to explode two objects with nested lists at the same time (to make this even more fun)

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EhUwtW95j_lIh-PdqRmv9dMBSNY3oFuSkVmr1NaqiiO_8w?e=QJbIDi

**Comment by adecler** [comment]
I was aware of this.  I sort of didn't want to deal with the case where you also have multiple objects as input (each with their list of list property).

I'll look into this as soon as the current list of pending PRs in the Grasshopper repo is empty.

**Comment by adecler** [comment]
Now working on the master:

![image](https://user-images.githubusercontent.com/16853390/108959397-4db51700-76af-11eb-90a1-aefa996e02f4.png)
