### ISSUE TITLE
Get the addition component to work with vectors from BHoM geometry param or variable param

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#565]
#### Description:

Currently, addition and multiplication with vectors from the geometry param and the Variable param does not work:

![image](https://user-images.githubusercontent.com/22005920/98789739-0017e580-2403-11eb-8fa8-f258abce0814.png)

They both fail is different ways, one with an error and one silently.

Related to the work done in https://github.com/BHoM/Grasshopper_Toolkit/pull/564

**Comment by adecler** [comment]
I am giving up on this one and will consider it as unsolvable. Fell free to prove me wrong 😄 

Despite the recent changes we made and the implementation of the `IGH_QuickCast` interface, `QC_Vec()` is actually never called. `MathComponents.Operations.OperationPerform(IGH_QuickCast operandA, IGH_QuickCast operandB, out IGH_QuickCast result)` does call `GetQuickCastType` but doesn't seem to follow up with the call to `QC_Vec` despite `GetQuickCastType` returning the correct type. 

I tried to do some digging with ILSpy but sadly the `Perform` method is relying on invoking from a dictionary of private method that we have no information about. My attempt to extract that list of methods through a C# component gave me nothing).
