### ISSUE TITLE
Removal of RunCode functionality from main branch/alpha/betas

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Grasshopper_Toolkit#614]
As discussed need and user story mapping needs to take place before any work on the RunCode component is carried out and as such the current prototype is not ready for deployment in installers.

Access should be removed from Grasshopper menu to avoid confusion for users.
![image](https://user-images.githubusercontent.com/15924573/110206389-375c4780-7e75-11eb-8ef5-47be020f501c.png)

**Comment by FraserGreenroyd** [comment]
This will in theory also resolve [this issue](https://github.com/BHoM/BHoM_Installer/issues/117) with installers for the beta as well which is preferable to attempting to make changes to the installer this close to beta release.

**Comment by adecler** [comment]
@al-fisher , I am already using this component quite a bit and I am not the only one. So, instead of removing it completely, could we instead address the reasons you dislike it to the point it needs to be removed ?
